import { motion } from 'framer-motion'
import Button from '../../components/Button'
import sticker02 from '../../assets/qiskit/Sticker 02.svg'
import sticker07 from '../../assets/qiskit/Sticker 07.svg'

const mockCertificates = [
  {
    id: 'mock-hackathon-1',
    certificateType: 'Hackathon',
    title: '1st Position',
    certificateId: 'QFF26-C-00001',
    issuedAt: '10 Sep 2026',
  },
  {
    id: 'mock-webinar-1',
    certificateType: 'Webinar',
    title: 'Participation',
    certificateId: 'QFF26-C-00002',
    issuedAt: '10 Sep 2026',
  },
]

const Certificates = () => {
  return (
    <motion.section className="detail-page" initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.35 }}>
      <div className="container detail-page__header">
        <div className="detail-page__intro">
          <p className="page-shell__eyebrow">Certificates</p>
          <h1>Your Qiskit Fall Fest 2026 Certificate.</h1>
          <p>
            Participants can receive certificates based on their involvement in Qiskit Fall Fest 2026. Whether you attend the main event, take part in the hackathon, join a workshop, or participate in the BootCamp, your participation can be recognized with the corresponding certificate.
          </p>
        </div>
        <div className="detail-page__visual">
          <img src={sticker07} alt="" className="detail-page__sticker" />
        </div>
      </div>

      <div className="container certificate-collection">
        <div className="detail-page__panel-copy">
          <p className="page-shell__eyebrow">My certificates</p>
          <h2>Your certificates</h2>
          <p>Certificates issued to you through Qiskit Fall Fest 2026.</p>
        </div>

        {mockCertificates.length > 0 ? (
          <div className="certificate-grid">
            {mockCertificates.map((certificate) => (
              <article key={certificate.id} className="certificate-card">
                <div>
                  <p className="certificate-card__type">{certificate.certificateType}</p>
                  <h3>{certificate.title}</h3>
                </div>
                <div className="certificate-card__details">
                  <div className="detail-info-item">
                    <span>Certificate ID</span>
                    <strong>{certificate.certificateId}</strong>
                  </div>
                  <p className="certificate-card__issued">Issued: {certificate.issuedAt}</p>
                </div>
                <div className="certificate-card__actions">
                  <Button kind="primary" disabled>View Certificate</Button>
                  <Button kind="secondary" disabled>Download PDF</Button>
                </div>
              </article>
            ))}
          </div>
        ) : (
          <div className="certificate-empty-state">
            <h3>No certificates have been issued yet.</h3>
            <p>Certificates you earn during Qiskit Fall Fest 2026 will appear here after they are generated by the organizers.</p>
          </div>
        )}
      </div>

      <div className="container detail-page__visual-row">
        <img src={sticker02} alt="" className="detail-page__sticker detail-page__sticker--small" />
      </div>

      <div className="container detail-page__cta-row">
        <Button to="/" kind="secondary">Back to home</Button>
        <Button to="/register" kind="primary">Register for the event</Button>
      </div>
    </motion.section>
  )
}

export default Certificates