BEGIN;

-- Add event categories without changing existing event identity or dates.
ALTER TABLE events
  ADD COLUMN IF NOT EXISTS event_type VARCHAR(32);

UPDATE events
SET event_type = CASE
  WHEN event_id = 'qff-2026' THEN 'GENERAL'
  WHEN event_id IN ('day-1', 'day-2', 'day-3', 'day-4') THEN 'GENERAL'
  ELSE 'GENERAL'
END
WHERE event_type IS NULL;

ALTER TABLE events
  ALTER COLUMN event_type SET DEFAULT 'GENERAL';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'events'::regclass
      AND contype = 'c'
      AND conname = 'events_event_type_check'
  ) THEN
    ALTER TABLE events
      ADD CONSTRAINT events_event_type_check
      CHECK (event_type IN ('GENERAL', 'HACKATHON', 'WEBINAR', 'WORKSHOP', 'BOOTCAMP'));
  END IF;
END
$$;

-- Fail closed before changing attendance uniqueness. Existing duplicate data
-- must be resolved explicitly rather than being deleted by this migration.
DO $$
DECLARE
  duplicate_report TEXT;
BEGIN
  SELECT string_agg(
    format('(event_id=%L, registration_id=%L, count=%s)', event_id, registration_id, duplicate_count),
    '; '
    ORDER BY event_id, registration_id
  )
  INTO duplicate_report
  FROM (
    SELECT event_id, registration_id, COUNT(*) AS duplicate_count
    FROM attendance
    GROUP BY event_id, registration_id
    HAVING COUNT(*) > 1
  ) duplicates;

  IF duplicate_report IS NOT NULL THEN
    RAISE EXCEPTION
      'Cannot apply attendance uniqueness migration: duplicate (event_id, registration_id) rows exist: %',
      duplicate_report;
  END IF;
END
$$;

DO $$
DECLARE
  null_event_count BIGINT;
BEGIN
  SELECT COUNT(*)
  INTO null_event_count
  FROM attendance
  WHERE event_id IS NULL;

  IF null_event_count > 0 THEN
    RAISE EXCEPTION
      'Cannot apply attendance migration: % attendance row(s) have NULL event_id',
      null_event_count;
  END IF;
END
$$;

ALTER TABLE attendance
  ALTER COLUMN event_id SET NOT NULL;

-- Remove only single-column UNIQUE constraints on registration_id. Primary keys,
-- foreign keys, and NOT NULL constraints are intentionally untouched.
DO $$
DECLARE
  constraint_record RECORD;
BEGIN
  FOR constraint_record IN
    SELECT con.conname
    FROM pg_constraint con
    JOIN pg_attribute att
      ON att.attrelid = con.conrelid
     AND att.attnum = con.conkey[1]
    WHERE con.conrelid = 'attendance'::regclass
      AND con.contype = 'u'
      AND array_length(con.conkey, 1) = 1
      AND att.attname = 'registration_id'
  LOOP
    EXECUTE format('ALTER TABLE attendance DROP CONSTRAINT %I', constraint_record.conname);
  END LOOP;
END
$$;

-- Remove an equivalent standalone unique index only if it is not backing a
-- remaining constraint. This handles databases where the legacy uniqueness
-- was created as an index rather than a table constraint.
DO $$
DECLARE
  index_record RECORD;
BEGIN
  FOR index_record IN
    SELECT index_name
    FROM (
      SELECT idx.relname AS index_name,
             indexrel.indkey,
             indexrel.indisunique,
             indexrel.indisprimary,
             EXISTS (
               SELECT 1
               FROM pg_constraint con
               WHERE con.conindid = indexrel.indexrelid
             ) AS backs_constraint
      FROM pg_class table_rel
      JOIN pg_index indexrel ON indexrel.indrelid = table_rel.oid
      JOIN pg_class idx ON idx.oid = indexrel.indexrelid
      WHERE table_rel.oid = 'attendance'::regclass
    ) attendance_indexes
    WHERE indisunique
      AND NOT indisprimary
      AND NOT backs_constraint
      AND indkey = ARRAY[
        (SELECT attnum FROM pg_attribute WHERE attrelid = 'attendance'::regclass AND attname = 'registration_id')::int2
      ]::int2vector
  LOOP
    EXECUTE format('DROP INDEX %I', index_record.index_name);
  END LOOP;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_index indexrel
    WHERE indexrel.indrelid = 'attendance'::regclass
      AND indexrel.indisunique
      AND indexrel.indkey = ARRAY[
        (SELECT attnum FROM pg_attribute WHERE attrelid = 'attendance'::regclass AND attname = 'event_id')::int2,
        (SELECT attnum FROM pg_attribute WHERE attrelid = 'attendance'::regclass AND attname = 'registration_id')::int2
      ]::int2vector
  ) THEN
    ALTER TABLE attendance
      ADD CONSTRAINT attendance_event_registration_key UNIQUE (event_id, registration_id);
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id VARCHAR(64) NOT NULL REFERENCES events(event_id),
  team_name VARCHAR(160) NOT NULL,
  team_lead_registration_id VARCHAR(32) REFERENCES registrations(registration_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (event_id, team_name)
);

CREATE TABLE IF NOT EXISTS team_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT NOT NULL REFERENCES teams(id),
  registration_id VARCHAR(32) NOT NULL REFERENCES registrations(registration_id),
  joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (team_id, registration_id)
);

CREATE TABLE IF NOT EXISTS hackathon_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT NOT NULL REFERENCES teams(id),
  placement VARCHAR(32) NOT NULL CHECK (placement IN ('FIRST_POSITION', 'FIRST_RUNNERS_UP', 'SECOND_RUNNERS_UP')),
  assigned_by BIGINT REFERENCES organizers(organizer_id),
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (team_id)
);

-- These indexes are created only when no equivalent index already exists.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_index
    WHERE indrelid = 'attendance'::regclass
      AND indkey = ARRAY[
        (SELECT attnum FROM pg_attribute WHERE attrelid = 'attendance'::regclass AND attname = 'event_id')::int2,
        (SELECT attnum FROM pg_attribute WHERE attrelid = 'attendance'::regclass AND attname = 'registration_id')::int2
      ]::int2vector
  ) THEN
    CREATE INDEX attendance_event_registration_idx ON attendance (event_id, registration_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_index
    WHERE indrelid = 'attendance'::regclass
      AND indkey = ARRAY[
        (SELECT attnum FROM pg_attribute WHERE attrelid = 'attendance'::regclass AND attname = 'registration_id')::int2
      ]::int2vector
  ) THEN
    CREATE INDEX attendance_registration_idx ON attendance (registration_id);
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS teams_event_idx ON teams (event_id);
CREATE INDEX IF NOT EXISTS team_members_team_idx ON team_members (team_id);
CREATE INDEX IF NOT EXISTS team_members_registration_idx ON team_members (registration_id);
CREATE INDEX IF NOT EXISTS hackathon_results_team_idx ON hackathon_results (team_id);

-- A unique index cannot span hackathon_results and teams. This trigger enforces
-- one occurrence of each placement within a HACKATHON event without adding a
-- redundant event_id column to hackathon_results.
CREATE OR REPLACE FUNCTION enforce_hackathon_result_rules()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  result_event_id VARCHAR(64);
  result_event_type VARCHAR(32);
BEGIN
  SELECT team.event_id, event.event_type
  INTO result_event_id, result_event_type
  FROM teams team
  JOIN events event ON event.event_id = team.event_id
  WHERE team.id = NEW.team_id;

  IF result_event_id IS NULL THEN
    RAISE EXCEPTION 'Hackathon result team % does not exist or has no event', NEW.team_id;
  END IF;

  IF result_event_type <> 'HACKATHON' THEN
    RAISE EXCEPTION 'Hackathon result team % belongs to non-hackathon event %', NEW.team_id, result_event_id;
  END IF;

  PERFORM pg_advisory_xact_lock(
    hashtextextended(result_event_id || ':' || NEW.placement, 0)
  );

  IF EXISTS (
    SELECT 1
    FROM hackathon_results existing_result
    JOIN teams existing_team ON existing_team.id = existing_result.team_id
    WHERE existing_team.event_id = result_event_id
      AND existing_result.placement = NEW.placement
      AND existing_result.id <> COALESCE(NEW.id, 0)
  ) THEN
    RAISE EXCEPTION 'Placement % is already assigned within hackathon event %', NEW.placement, result_event_id;
  END IF;

  RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS hackathon_result_rules_trigger ON hackathon_results;

CREATE TRIGGER hackathon_result_rules_trigger
  BEFORE INSERT OR UPDATE OF team_id, placement ON hackathon_results
  FOR EACH ROW
  EXECUTE FUNCTION enforce_hackathon_result_rules();

COMMIT;